#!/bin/bash

status=$(nmcli n connectivity | grep -oE "none")
essid=$(nmcli c | grep wlp0s20f3 | awk '{print ($1)}')

if [ $status ] ; then
    icon="󰤮"
    text=""
    col="#dc014c"

else
    icon="󰖩"
    text="${essid}"
    col="#8f77b5"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi

